
model: 
  arch_name: "megaloc"
  dataset_name: "mp16"
  pred_model_name: "geoclip"
  head_type: "multik"
  K_km: [1.0, 5.0, 10.0, 25.0, 50.0, 100.0, 200.0, 500.0, 1000.0]
  learning_rate: 0.0001
  weight_decay: 0.00001
  scheduler: 'cosine'
  warmup_steps: 10
  min_lr: 0.00001
  loss_alpha: 1.0
  loss_beta: 0.1
  batch_size: 32
  num_workers: 8

trainer: 
  max_steps: 500000
  precision: 'bf16-mixed' 
  accelerator: 'auto'
  devices: 'auto'
  strategy: 'auto'
  enable_progress_bar: False


checkpoint: True 
logger: True 
